name: Java CI with Maven

on:
  push:
    branches: [ main ]  # Changed to 'main'

jobs:
  build:
    runs-on: self-hosted  # Keep as 'self-hosted' if you're using a custom runner, or use 'ubuntu-latest' for GitHub's hosted runner.

    env:
      GREEDING: "Hello, this is a greeting environment variable"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        timeout-minutes: 1 # Exit if this step exceeds 60 seconds

      - name: Verify JAR File
        run: ls -l /home/ubuntu/actions-runner/_work/cicd_pipeliine/cicd_pipeliine/target/
        timeout-minutes: 1 # Exit if this step exceeds 60 seconds

      - name: Stop any process running on port 80
        run: |
          if sudo lsof -t -i:80 > /dev/null; then
            sudo kill -9 $(sudo lsof -t -i:80)
          fi
        timeout-minutes: 1 # Exit if this step exceeds 60 seconds

      - name: Execute Jar File
        run: sudo java -jar /home/ubuntu/actions-runner/_work/cicd_pipeliine/cicd_pipeliine/target/test_project-0.0.1-SNAPSHOT.jar &
        timeout-minutes: 1 # Exit if this step exceeds 60 seconds
