name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout for the job to prevent hanging indefinitely

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Display current directory and list files (debugging step)
      - name: Display Current Directory and Files
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in the repository:"
          ls -la

      # Step 4: Build the project with Maven
      - name: Build with Maven
        timeout-minutes: 10
        run: |
          echo "Starting Maven build..."
          mvn -B package --file pom.xml -DskipTests -X || { echo "Maven build failed"; exit 1; }
          echo "Maven build completed successfully."

      # Step 5: Verify .jar File Creation
      - name: Check for JAR File
        run: |
          echo "Checking for the generated JAR file..."
          JAR_PATH=$(find ./target -name "*.jar" -print -quit)
          if [ -z "$JAR_PATH" ]; then
            echo "Error: JAR file not found in the target directory."
            exit 1
          fi
          echo "JAR file found: $JAR_PATH"

      # Step 6: Stop any running process on port 80 (if needed)
      - name: Stop Existing Process on Port 80
        run: |
          echo "Stopping any existing process running on port 80..."
          sudo lsof -t -i:80 | xargs -r sudo kill -9 || echo "No process running on port 80"

      # Step 7: Execute the Spring Boot JAR file
      - name: Execute Jar File
        run: |
          JAR_PATH=$(find ./target -name "*.jar" -print -quit)  # Automatically find the JAR file
          echo "Starting the Spring Boot application with JAR file: $JAR_PATH"
          sudo java -jar $JAR_PATH --server.port=80 > app.log 2>&1 &
          
          echo "Waiting for the application to start..."
          timeout=60
          while ! grep -q 'Started' app.log; do
            sleep 2
            timeout=$((timeout - 2))
            if [ $timeout -le 0 ]; then
              echo "Application failed to start within 60 seconds."
              cat app.log  # Display logs for debugging
              exit 1
            fi
          done
          echo "Application started successfully."

      # Step 8: Display the last 20 lines of application logs
      - name: Display Application Logs
        run: tail -n 20 app.log
