name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          GREETING: ${{ secrets.GREETING }}
        run: mvn -B package --file pom.xml -X
      - name: Execute Jar File
        run: |
          # Kill any process on port 80 (only if needed)
          sudo lsof -t -i:80 | xargs -r sudo kill -9
          # Run the jar file (make sure the path is correct)
          sudo java -jar /home/ubuntu/actions-runner/_work/cicd_pipeliine/cicd_pipeliine/target/test_project-0.0.1-SNAPSHOT.jar &
